name = "cinecensus"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Uncomment and fill in for production
# [vars]
# PUBLIC_SUPABASE_URL = ""
# PUBLIC_SUPABASE_ANON_KEY = ""
# OMDB_API_KEY = ""
